import FWCore.ParameterSet.Config as cms

from Configuration.Generator.Pythia8CommonSettings_cfi import *
from Configuration.Generator.MCTunesRun3ECM13p6TeV.PythiaCP5Settings_cfi import *
from Configuration.Generator.PSweightsPythia.PythiaPSweightsSettings_cfi import *

import math

# ---------------------------------------------------------------------------
# T2cc  |  mStop = 1000 GeV  |  DeltaM = 10 15 20 25 30 40 50 60 70 80
# Generated by work/fragments/make_fragments.py (baseline: approved McM request NPS-RunIII2024Summer24FSGenPremix-00007)
# ---------------------------------------------------------------------------

baseSLHATable="""
BLOCK MASS  # Mass Spectrum
# PDG code           mass       particle
   1000001     1.00000000E+05   # ~d_L
   2000001     1.00000000E+05   # ~d_R
   1000002     1.00000000E+05   # ~u_L
   2000002     1.00000000E+05   # ~u_R
   1000003     1.00000000E+05   # ~s_L
   2000003     1.00000000E+05   # ~s_R
   1000004     1.00000000E+05   # ~c_L
   2000004     1.00000000E+05   # ~c_R
   1000005     1.00000000E+05   # ~b_1
   2000005     1.00000000E+05   # ~b_2
   1000006     %MSTOP%          # ~t_1
   2000006     1.00000000E+05   # ~t_2
   1000011     1.00000000E+05   # ~e_L
   2000011     1.00000000E+05   # ~e_R
   1000012     1.00000000E+05   # ~nu_eL
   1000013     1.00000000E+05   # ~mu_L
   2000013     1.00000000E+05   # ~mu_R
   1000014     1.00000000E+05   # ~nu_muL
   1000015     1.00000000E+05   # ~tau_1
   2000015     1.00000000E+05   # ~tau_2
   1000016     1.00000000E+05   # ~nu_tauL
   1000021     1.00000000E+05    # ~g
   1000022     %MLSP%           # ~chi_10
   1000023     1.00000000E+05   # ~chi_20
   1000025     1.00000000E+05   # ~chi_30
   1000035     1.00000000E+05   # ~chi_40
   1000024     1.00000000E+05   # ~chi_1+
   1000037     1.00000000E+05   # ~chi_2+

# DECAY TABLE
#         PDG            Width
DECAY   1000001     0.00000000E+00   # sdown_L decays
DECAY   2000001     0.00000000E+00   # sdown_R decays
DECAY   1000002     0.00000000E+00   # sup_L decays
DECAY   2000002     0.00000000E+00   # sup_R decays
DECAY   1000003     0.00000000E+00   # sstrange_L decays
DECAY   2000003     0.00000000E+00   # sstrange_R decays
DECAY   1000004     0.00000000E+00   # scharm_L decays
DECAY   2000004     0.00000000E+00   # scharm_R decays
DECAY   1000005     0.00000000E+00   # sbottom1 decays
DECAY   2000005     0.00000000E+00   # sbottom2 decays
DECAY   1000006     1.00000000E+00   # stop1 decays
    1.00000000E+00    2    1000022      4     # stop -> LSP + charm
DECAY   2000006     0.00000000E+00   # stop2 decays

DECAY   1000011     0.00000000E+00   # selectron_L decays
DECAY   2000011     0.00000000E+00   # selectron_R decays
DECAY   1000012     0.00000000E+00   # snu_elL decays
DECAY   1000013     0.00000000E+00   # smuon_L decays
DECAY   2000013     0.00000000E+00   # smuon_R decays
DECAY   1000014     0.00000000E+00   # snu_muL decays
DECAY   1000015     0.00000000E+00   # stau_1 decays
DECAY   2000015     0.00000000E+00   # stau_2 decays
DECAY   1000016     0.00000000E+00   # snu_tauL decays
DECAY   1000021     0.00000000E+00   # gluino decays
DECAY   1000022     0.00000000E+00   # neutralino1 decays
DECAY   1000023     0.00000000E+00   # neutralino2 decays
DECAY   1000024     0.00000000E+00   # chargino1+ decays
DECAY   1000025     0.00000000E+00   # neutralino3 decays
DECAY   1000035     0.00000000E+00   # neutralino4 decays
DECAY   1000037     0.00000000E+00   # chargino2+ decays
"""

generator = cms.EDFilter("Pythia8GeneratorFilter",
    maxEventsToPrint = cms.untracked.int32(1),
    pythiaPylistVerbosity = cms.untracked.int32(1),
    filterEfficiency = cms.untracked.double(1.0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    comEnergy = cms.double(13600.),
    RandomizedParameters = cms.VPSet(),
)

model = "T2cc"

# MLM matching parameters, indexed by mStop.
#
#   qcut    -- UNCHANGED, inherited verbatim from the approved request. This is a
#              value we *choose*, not one we measure, and the efficiencies below
#              were measured with exactly these qcut values: changing qcut would
#              invalidate them.
#   tru_eff -- REPLACED with our own measurement (see provenance below). The table
#              we inherited was measured on a different gridpack, and disagreed
#              with our gridpacks by up to 26% (worst point in this family).
#
# Provenance of tru_eff
#   Measured in a private GEN validation run (CMSSW_14_0_22_patch1, HTCondor, 2026-08),
#   using these very fragments with a single mass point left in each. Efficiency is
#   accepted/tried as reported by the Pythia8 MLM matching veto, i.e. the same
#   quantity McM calls the match efficiency.
#   Statistics: 331,000 generated events over 19 distinct mStop values
#   (every mStop value that appears in this request was measured; none is interpolated).
#   Topology and LSP mass are folded together: at fixed mStop the topologies and
#   DeltaM values we cross-checked agreed to within 1.0 sigma (22 points, 6 groups).
#   That is expected -- MLM matching happens between the hard process and the parton
#   shower, while the SUSY decay chain is applied afterwards.
#   T2cc/T2ttC/T2bWC all read the same gridpack (SMS-StopStop, xqcut 30), so there is
#   nothing topology-dependent left for matching to see.
#
# Binning rule
#   Steps are placed where qcut steps, so that qcut(mass) is bit-for-bit what the
#   approved request had. Within each qcut interval the measured points are tested
#   against a single constant; if they are consistent (chi2 p-value >= 0.05) they
#   are merged and the row carries their weighted mean. 4 of the 5 qcut intervals
#   passed unchanged. Intervals that failed are split further (still inside the same
#   qcut interval, so qcut is still untouched); those rows are marked SPLIT below.
#   Point-by-point values are deliberately NOT used: at 2k events per point the
#   binomial spread alone is about +-1.0 percentage point, which would put noise
#   into the table as if it were structure.
#
# Columns below: <upper bound>  qcut  tru_eff  [n points, events, chi2/ndf, p]
def matchParams(mass):
  if mass < 399: return 62., 0.3440     # 300-350: 2 pts, 200,000 ev, chi2/ndf 1.8/1, p 0.179, SPLIT
  elif mass < 649: return 62., 0.2878   # 400-600: 5 pts, 10,000 ev, chi2/ndf 3.2/4, p 0.531, SPLIT
  elif mass < 749: return 64., 0.2692   # 650-700: 2 pts, 4,000 ev, chi2/ndf 0.1/1, p 0.748
  elif mass < 849: return 66., 0.2557   # 750-800: 2 pts, 4,000 ev, chi2/ndf 0.1/1, p 0.744
  elif mass < 949: return 68., 0.2538   # 850-900: 2 pts, 4,000 ev, chi2/ndf 1.5/1, p 0.217
  elif mass < 1249: return 70., 0.2431  # 950-1200: 6 pts, 109,000 ev, chi2/ndf 7.2/5, p 0.206
  # Everything below this line is the approved request's table, untouched.
  # No point in this request reaches it (highest mStop here is 1200); it is kept so
  # that the inherited table stays diffable outside our grid. check_eff asserts
  # that no requested mass falls through to these rows.
  elif mass < 1299: return 70., 0.242
  elif mass < 1349: return 70., 0.241
  elif mass < 1399: return 70., 0.237
  elif mass < 1449: return 70., 0.239
  elif mass < 1499: return 70., 0.241
  elif mass < 1549: return 70., 0.235
  elif mass < 1599: return 70., 0.239
  elif mass < 1649: return 70., 0.239
  elif mass < 1699: return 70., 0.237
  elif mass < 1749: return 70., 0.241
  elif mass < 1799: return 70., 0.237
  elif mass < 1849: return 70., 0.237
  elif mass < 1899: return 70., 0.240
  elif mass < 1949: return 70., 0.241
  elif mass < 1999: return 70., 0.244
  elif mass < 2049: return 70., 0.246
  elif mass < 2099: return 70., 0.249
  elif mass < 2149: return 70., 0.246
  elif mass < 2199: return 70., 0.246
  elif mass < 2249: return 70., 0.251
  elif mass < 2299: return 70., 0.249
  elif mass < 2349: return 70., 0.257
  elif mass < 2399: return 70., 0.257
  elif mass < 2449: return 70., 0.261
  elif mass < 2499: return 70., 0.264
  elif mass < 2549: return 70., 0.266
  else: return 70., 0.243

# Points contained in this request — design plane is (mStop, DeltaM); mStop is fixed in this file.
# Points are written as the DeltaM grid rather than enumerated: listing only mLSP would hide
# DeltaM, our design axis.
#
# The DeltaM grid is non-uniform (step 5 up to 30, step 10 above). Ground: measured Run2
# compressed-stop grids — T2bW_X05 / T2tt 4-body Run2 production used exactly these 10 values.
# "Where to densify" is decided by the eff(DeltaM) curve, and that curve is an output of this
# request — the circularity is broken not by calculation but by actually running that grid.
MSTOP = 1000
DM_POINTS = [10, 15, 20, 25, 30, 40, 50, 60, 70, 80]

# Events per point [k]. A function of mStop alone, so every point in this request receives the
# same value (= all ConfigWeights equal = uniform sharing). Nothing inside this file is decided
# by this number; it fixes only Sum(wgt) = the total reported to McM.
# Its inputs (goalLumi 400 · xsec · cap 1000k / floor 100k) live outside this file — in the
# request CSV 'events' column and in the presentation's grid justification.
NEV = 100

mpoints = [(MSTOP, MSTOP - dm, NEV) for dm in DM_POINTS]

qcut, tru_eff = matchParams(1000)

# Decision (2026-08-15): tru_eff is not hard-coded; it is taken from the table above (rule (b)).
#
#   mcm_eff = efficiency reported to McM, defined as "final/generated over the whole request",
#   so that Sum(wgt) equals the final event total we intend.
#   This request holds a single mStop and the table is indexed by mStop only, so every point
#   receives the same tru_eff -> the overall efficiency is that value -> ratio 1 is the
#   structurally expected result. (Approved -00007 is also a single mStop (1050), with
#   mcm_eff = tru_eff = 0.248. The division itself is a relic of the old layout where one
#   request carried several mStops.)
mcm_eff = tru_eff

# The tru_eff values above are our own measurement on our own gridpacks (see the provenance
# comment on the table). They replace the approved request's T2tt numbers, which were measured
# on a different gridpack and were off by up to 26% at the low end of our grid.
# This number affects only the efficiency reported to McM (= how many events production must
# generate); with ratio 1 it does not affect ConfigWeight or the grid shape.

for mstop, mlsp, nev in mpoints:
    wgt = nev * (mcm_eff / tru_eff)
    if mlsp == 0:
        mlsp = 1

    slhatable = baseSLHATable.replace('%MSTOP%', '%e' % mstop)
    slhatable = slhatable.replace('%MLSP%',  '%e' % mlsp)

    basePythiaParameters = cms.PSet(
        pythia8CommonSettingsBlock,
        pythia8CP5SettingsBlock,
        pythia8PSweightsSettingsBlock,
        processParameters = cms.vstring(
            'JetMatching:setMad = off',
            'JetMatching:scheme = 1',
            'JetMatching:merge = on',
            'JetMatching:jetAlgorithm = 2',
            'JetMatching:etaJetMax = 5.',
            'JetMatching:coneRadius = 1.',
            'JetMatching:slowJetPower = 1',
            'JetMatching:qCut = %.0f' % qcut, #this is the actual merging scale
            'JetMatching:nQmatch = 5', #4 corresponds to 4-flavour scheme (no matching of b-quarks), 5 for 5-flavour scheme
            'JetMatching:nJetMax = 2', #number of partons in born matrix element for highest multiplicity
            'JetMatching:doShowerKt = off', #off for MLM matching, turn on for shower-kT matching
            '6:m0 = 172.5',
            'Check:abortIfVeto = on',
            'TauDecays:externalMode=2',
            'SLHA:allowOnlyOffShell = on',   # no on-shell path exists in the compressed region
            '24:mMin = 0.1',                 # W mass sampling floor; the default 10 would switch decays off at DeltaM 10
        ),
        parameterSets = cms.vstring('pythia8CommonSettings',
                                    'pythia8CP5Settings',
                                    'pythia8PSweightsSettings',
                                    'processParameters'
                                    )
    )
    generator.RandomizedParameters.append(
        cms.PSet(
            ConfigWeight = cms.double(wgt),
            GridpackPath =  cms.string('/cvmfs/cms-griddata.cern.ch/phys_generator/gridpacks_tarball/pp/13p6TeV/madgraph/SMS-StopStop/SMS-StopStop_mStop-1000_slc7_amd64_gcc10_CMSSW_12_4_8_tarball.tar.xz'),
            ConfigDescription = cms.string('%s_%i_%i' % (model, mstop, mlsp)),
            SLHATableForPythia8 = cms.string('%s' % slhatable),
            PythiaParameters = basePythiaParameters,
        ),
    )

ProductionFilterSequence = cms.Sequence(generator)
