import FWCore.ParameterSet.Config as cms

from Configuration.Generator.Pythia8CommonSettings_cfi import *
from Configuration.Generator.MCTunesRun3ECM13p6TeV.PythiaCP5Settings_cfi import *
from Configuration.Generator.PSweightsPythia.PythiaPSweightsSettings_cfi import *

import math

# ---------------------------------------------------------------------------
# T2cc  |  mStop = 850 GeV  |  DeltaM = 10 15 20 25 30 40 50 60 70 80
# Generated by work/fragments/make_fragments.py (baseline: approved McM request NPS-RunIII2024Summer24FSGenPremix-00007)
# ---------------------------------------------------------------------------

baseSLHATable="""
BLOCK MASS  # Mass Spectrum
# PDG code           mass       particle
   1000001     1.00000000E+05   # ~d_L
   2000001     1.00000000E+05   # ~d_R
   1000002     1.00000000E+05   # ~u_L
   2000002     1.00000000E+05   # ~u_R
   1000003     1.00000000E+05   # ~s_L
   2000003     1.00000000E+05   # ~s_R
   1000004     1.00000000E+05   # ~c_L
   2000004     1.00000000E+05   # ~c_R
   1000005     1.00000000E+05   # ~b_1
   2000005     1.00000000E+05   # ~b_2
   1000006     %MSTOP%          # ~t_1
   2000006     1.00000000E+05   # ~t_2
   1000011     1.00000000E+05   # ~e_L
   2000011     1.00000000E+05   # ~e_R
   1000012     1.00000000E+05   # ~nu_eL
   1000013     1.00000000E+05   # ~mu_L
   2000013     1.00000000E+05   # ~mu_R
   1000014     1.00000000E+05   # ~nu_muL
   1000015     1.00000000E+05   # ~tau_1
   2000015     1.00000000E+05   # ~tau_2
   1000016     1.00000000E+05   # ~nu_tauL
   1000021     1.00000000E+05    # ~g
   1000022     %MLSP%           # ~chi_10
   1000023     1.00000000E+05   # ~chi_20
   1000025     1.00000000E+05   # ~chi_30
   1000035     1.00000000E+05   # ~chi_40
   1000024     1.00000000E+05   # ~chi_1+
   1000037     1.00000000E+05   # ~chi_2+

# DECAY TABLE
#         PDG            Width
DECAY   1000001     0.00000000E+00   # sdown_L decays
DECAY   2000001     0.00000000E+00   # sdown_R decays
DECAY   1000002     0.00000000E+00   # sup_L decays
DECAY   2000002     0.00000000E+00   # sup_R decays
DECAY   1000003     0.00000000E+00   # sstrange_L decays
DECAY   2000003     0.00000000E+00   # sstrange_R decays
DECAY   1000004     0.00000000E+00   # scharm_L decays
DECAY   2000004     0.00000000E+00   # scharm_R decays
DECAY   1000005     0.00000000E+00   # sbottom1 decays
DECAY   2000005     0.00000000E+00   # sbottom2 decays
DECAY   1000006     1.00000000E+00   # stop1 decays
    1.00000000E+00    2    1000022      4     # stop -> LSP + charm
DECAY   2000006     0.00000000E+00   # stop2 decays

DECAY   1000011     0.00000000E+00   # selectron_L decays
DECAY   2000011     0.00000000E+00   # selectron_R decays
DECAY   1000012     0.00000000E+00   # snu_elL decays
DECAY   1000013     0.00000000E+00   # smuon_L decays
DECAY   2000013     0.00000000E+00   # smuon_R decays
DECAY   1000014     0.00000000E+00   # snu_muL decays
DECAY   1000015     0.00000000E+00   # stau_1 decays
DECAY   2000015     0.00000000E+00   # stau_2 decays
DECAY   1000016     0.00000000E+00   # snu_tauL decays
DECAY   1000021     0.00000000E+00   # gluino decays
DECAY   1000022     0.00000000E+00   # neutralino1 decays
DECAY   1000023     0.00000000E+00   # neutralino2 decays
DECAY   1000024     0.00000000E+00   # chargino1+ decays
DECAY   1000025     0.00000000E+00   # neutralino3 decays
DECAY   1000035     0.00000000E+00   # neutralino4 decays
DECAY   1000037     0.00000000E+00   # chargino2+ decays
"""

generator = cms.EDFilter("Pythia8GeneratorFilter",
    maxEventsToPrint = cms.untracked.int32(1),
    pythiaPylistVerbosity = cms.untracked.int32(1),
    filterEfficiency = cms.untracked.double(1.0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    comEnergy = cms.double(13600.),
    RandomizedParameters = cms.VPSet(),
)

model = "T2cc"

# MLM matching scale. Taken from the approved-request table unchanged (2026-08-14 decision:
# a function of mStop, not a constant).
# Why topology-independent: matching happens between the gridpack (hard process) and the shower;
# decays come after. As long as T2cc/T2ttC/T2bWC share one gridpack (SMS-StopStop, xqcut 30)
# there is nothing topology-dependent to split.
def matchParams(mass):
  if mass < 649: return 62., 0.274
  elif mass < 699: return 64., 0.269
  elif mass < 749: return 64., 0.269
  elif mass < 799: return 66., 0.259
  elif mass < 849: return 66., 0.261
  elif mass < 899: return 68., 0.257
  elif mass < 949: return 68., 0.252
  elif mass < 999: return 70., 0.250
  elif mass < 1049: return 70., 0.248
  elif mass < 1099: return 70., 0.248
  elif mass < 1149: return 70., 0.249
  elif mass < 1199: return 70., 0.242
  elif mass < 1249: return 70., 0.239
  elif mass < 1299: return 70., 0.242
  elif mass < 1349: return 70., 0.241
  elif mass < 1399: return 70., 0.237
  elif mass < 1449: return 70., 0.239
  elif mass < 1499: return 70., 0.241
  elif mass < 1549: return 70., 0.235
  elif mass < 1599: return 70., 0.239
  elif mass < 1649: return 70., 0.239
  elif mass < 1699: return 70., 0.237
  elif mass < 1749: return 70., 0.241
  elif mass < 1799: return 70., 0.237
  elif mass < 1849: return 70., 0.237
  elif mass < 1899: return 70., 0.240
  elif mass < 1949: return 70., 0.241
  elif mass < 1999: return 70., 0.244
  elif mass < 2049: return 70., 0.246
  elif mass < 2099: return 70., 0.249
  elif mass < 2149: return 70., 0.246
  elif mass < 2199: return 70., 0.246
  elif mass < 2249: return 70., 0.251
  elif mass < 2299: return 70., 0.249
  elif mass < 2349: return 70., 0.257
  elif mass < 2399: return 70., 0.257
  elif mass < 2449: return 70., 0.261
  elif mass < 2499: return 70., 0.264
  elif mass < 2549: return 70., 0.266
  ### Just for testing
  else: return 70., 0.243

# Points contained in this request — design plane is (mStop, DeltaM); mStop is fixed in this file.
# Points are written as the DeltaM grid rather than enumerated: listing only mLSP would hide
# DeltaM, our design axis.
#
# The DeltaM grid is non-uniform (step 5 up to 30, step 10 above). Ground: measured Run2
# compressed-stop grids — T2bW_X05 / T2tt 4-body Run2 production used exactly these 10 values.
# "Where to densify" is decided by the eff(DeltaM) curve, and that curve is an output of this
# request — the circularity is broken not by calculation but by actually running that grid.
MSTOP = 850
DM_POINTS = [10, 15, 20, 25, 30, 40, 50, 60, 70, 80]

# Events per point [k]. A function of mStop alone, so every point in this request receives the
# same value (= all ConfigWeights equal = uniform sharing). Nothing inside this file is decided
# by this number; it fixes only Sum(wgt) = the total reported to McM.
# Its inputs (goalLumi 400 · xsec · cap 1000k / floor 100k) live outside this file — in the
# request CSV 'events' column and in the presentation's grid justification.
NEV = 100

mpoints = [(MSTOP, MSTOP - dm, NEV) for dm in DM_POINTS]

qcut, tru_eff = matchParams(850)

# Decision (2026-08-15): tru_eff is not hard-coded; it is taken from the table above (rule (b)).
#
#   mcm_eff = efficiency reported to McM, defined as "final/generated over the whole request",
#   so that Sum(wgt) equals the final event total we intend.
#   This request holds a single mStop and the table is indexed by mStop only, so every point
#   receives the same tru_eff -> the overall efficiency is that value -> ratio 1 is the
#   structurally expected result. (Approved -00007 is also a single mStop (1050), with
#   mcm_eff = tru_eff = 0.248. The division itself is a relic of the old layout where one
#   request carried several mStops.)
mcm_eff = tru_eff

# The table values were measured by the approved-request authors with T2tt. Whether they hold
# for our topologies (T2cc/T2ttC/T2bWC) and the compressed grid (DeltaM 10-80) is not yet known
# -> to be re-measured in a private GEN validation and updated.
# Today this number affects only the efficiency reported to McM (= produced amount); with ratio 1
# it does not affect ConfigWeight or the grid shape.

for mstop, mlsp, nev in mpoints:
    wgt = nev * (mcm_eff / tru_eff)
    if mlsp == 0:
        mlsp = 1

    slhatable = baseSLHATable.replace('%MSTOP%', '%e' % mstop)
    slhatable = slhatable.replace('%MLSP%',  '%e' % mlsp)

    basePythiaParameters = cms.PSet(
        pythia8CommonSettingsBlock,
        pythia8CP5SettingsBlock,
        pythia8PSweightsSettingsBlock,
        processParameters = cms.vstring(
            'JetMatching:setMad = off',
            'JetMatching:scheme = 1',
            'JetMatching:merge = on',
            'JetMatching:jetAlgorithm = 2',
            'JetMatching:etaJetMax = 5.',
            'JetMatching:coneRadius = 1.',
            'JetMatching:slowJetPower = 1',
            'JetMatching:qCut = %.0f' % qcut, #this is the actual merging scale
            'JetMatching:nQmatch = 5', #4 corresponds to 4-flavour scheme (no matching of b-quarks), 5 for 5-flavour scheme
            'JetMatching:nJetMax = 2', #number of partons in born matrix element for highest multiplicity
            'JetMatching:doShowerKt = off', #off for MLM matching, turn on for shower-kT matching
            '6:m0 = 172.5',
            'Check:abortIfVeto = on',
            'TauDecays:externalMode=2',
            'SLHA:allowOnlyOffShell = on',   # no on-shell path exists in the compressed region
            '24:mMin = 0.1',                 # W mass sampling floor; the default 10 would switch decays off at DeltaM 10
        ),
        parameterSets = cms.vstring('pythia8CommonSettings',
                                    'pythia8CP5Settings',
                                    'pythia8PSweightsSettings',
                                    'processParameters'
                                    )
    )
    generator.RandomizedParameters.append(
        cms.PSet(
            ConfigWeight = cms.double(wgt),
            GridpackPath =  cms.string('/cvmfs/cms-griddata.cern.ch/phys_generator/gridpacks_tarball/pp/13p6TeV/madgraph/SMS-StopStop/SMS-StopStop_mStop-850_slc7_amd64_gcc10_CMSSW_12_4_8_tarball.tar.xz'),
            ConfigDescription = cms.string('%s_%i_%i' % (model, mstop, mlsp)),
            SLHATableForPythia8 = cms.string('%s' % slhatable),
            PythiaParameters = basePythiaParameters,
        ),
    )

ProductionFilterSequence = cms.Sequence(generator)
